
DROP TABLE USERS IF EXISTS ;

CREATE TABLE USERS (
  USERNAME VARCHAR(50) PRIMARY KEY ,
  PASSWORD VARCHAR(50) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  USER_ID INT AUTO_INCREMENT UNIQUE
);

DROP TABLE USER_ROLE IF EXISTS ;

CREATE TABLE USER_ROLE (
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY ,
  USERNAME VARCHAR(50) ,
  ROLE VARCHAR(50),
  UNIQUE (USERNAME,ROLE)
);

DROP TABLE FLAT IF EXISTS ;

CREATE TABLE FLAT(
  FLAT_ID INT PRIMARY KEY ,
  OWNER_ID INT REFERENCES USERS(USER_ID),
  OWNERS_NAME VARCHAR(50),
  PROPERTY_TYPE VARCHAR(50),
  LOCATION VARCHAR(50),
  CITY VARCHAR(50),
  SQ_FEET INT,
  BED INT,
  BATH INT,
  IMAGE BLOB
);

DROP TABLE ADD IF EXISTS;

CREATE TABLE ADD (
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  TITLE VARCHAR(100),
  FLAT_ID INT REFERENCES FLAT(FLAT_ID),
  OWNER_ID INT REFERENCES USERS(USER_ID),
  OWNERS_NAME VARCHAR (50),
  PROPERTY_TYPE VARCHAR(50),
  PURPOSE VARCHAR(50),
  LOCATION  VARCHAR(50),
  CITY VARCHAR (50),
  DETAILS VARCHAR (250),
  PRICE INT ,
  SQ_FEET INT,
  BED INT,
  BATH INT,
  IMAGE BLOB
);




DROP TRIGGER INSERT_FLAT IF EXISTS ;

CREATE TRIGGER INSERT_FLAT
  BEFORE INSERT
  ON ADD
  FOR EACH ROW
  CALL "term.project.homerental.trigger.InsertFlat"